### PR TITLE
2015 08 17 and july updates

### LINKED ISSUE #6: New API August 15, 2015
https://core.telegram.org/bots/api-changelog
- Added new type Voice and new method sendVoice for sending voice messages.
- Earlier Audio and sendAudio should now be used for sending music files. Telegram clients will show such files in the in-app music player. If you were using sendAudio for your bot to send voice messages, please use sendVoice instead.
- Added optional fields performer, title to the Audio object and sendAudio method.
- Added optional field voice to the Message object.

### PR DESCRIPTION
**Pull request by FichteFoll**
Also includes updates from July, which haven't been updated either which I noticed later.

Refer to https://core.telegram.org/bots/api-changelog#august-15-2015 and https://core.telegram.org/bots/api-changelog#july-2015.

Closes #6.

### CODE REVIEW

**Comment by FichteFoll** [comment]
~~I'm also including the september changes in this pull request and working on a convenience method for downloading files.~~ But that needs to wait till tomorrow when I can actually test this stuff.

Edit: Decided to split off

**Comment by nisarul** [comment]
@FichteFoll Wow wonderful.
Hope that @Surye will merge it soon.

**Comment by FichteFoll** [comment]
I successfully downloaded multiple files, photos and documents, with the just commited changes.

I'm unsure of the interface I used since I subclassed `TelegramBotRPCRequest`, but open for suggestions. Just getting this out so that others can start experimenting with my fork.

**Comment by FichteFoll** [comment]
I decided to split the get_file addition into a separate PR since that one is not as easy to review as this one: #12.

**Pull request merged**
